openapi: "3.0.3"
info:
  version: 0.0.1
  title: Doggoschool API
  description: A small sample API to grasp the basics of the OpenAPI Specification
servers:
  - url: http://localhost:8080/api
paths:
  /ponies:
    get:
      summary: List all doggos
      operationId: getDogs
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time
          required: false
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: An paged array of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DogDTO"
    post:
      summary: introduce a new doggo to the doggos
      operationId: addDog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DogDTO"
      responses:
        201:
          description: added the doggo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DogDTO"
components:
  schemas:
    DogDTO:
      required:
        - name
        - breed
        - owner
        - food
        - dogschool
      properties:
        id:
          type: integer
          example: 42
          minimum: 0
          readOnly: true
        name:
          type: string
          minLength: 1
          example: Kira
        breed:
          type: string
          minLength: 1
          example: Golden Retriever
        owner:
          type: owner
          minLength: 1
          example: Kristoffer Jonas Klauß
        food:
          type: string
          minLength: 1
          example: t-bone Steak
        dogschool:
          type: dogschool
          minLength: 1
          example: Dogschool Zurich

